import type { Metadata } from "next";
import '../styles/globals.css';
import Navbar from "@/src/components/Navbar";


export const metadata: Metadata = {
  title: "Dome Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
